language: python
env:
    - DJANGO_VERSION=1.4.15
    - DJANGO_VERSION=1.5.10
    - DJANGO_VERSION=1.6.7
    - DJANGO_VERSION=1.7
python:
    - 3.4
    - 3.3
    - 3.2
    - 2.7
    - 2.6
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install -r tests/test_requirements.txt
  - pip install coveralls
script:
  - python manage.py test
  - coverage run --source=snips manage.py test
after_success: coveralls
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 2.6
      env: DJANGO_VERSION=1.7
    - python: 3.2
      env: DJANGO_VERSION=1.4.15
    - python: 3.3
      env: DJANGO_VERSION=1.4.15
    - python: 3.3
      env: DJANGO_VERSION=1.5.10
    - python: 3.4
      env: DJANGO_VERSION=1.4.15
    - python: 3.4
      env: DJANGO_VERSION=1.5.10
    - python: 3.4
      env: DJANGO_VERSION=1.6.7

